Add a cryptosmite page and add links to it under "the fog" section
CoolElectronics/sh1mmer.me pull request #125
Opened 2024-03-26 19:33 UTC by ThisCatLikesCrypto

It may be worth adding images to cryptosmite.html at some point and it's not perfect but I thought it may be a good idea to have a page for this.

Currently I've hosted a (very slightly different, but pretty much the same) version at https://wilburwilliams.uk/sh1mmer/cryptosmite

2024-03-31 16:40 UTC, NotDarkn requested changes
- change "Cryptosmite" to "CryptoSmite" in `cryptosmite.html`
- change "cryptosmite" to "CryptoSmite" in `index.html`
- remove "It is possible to downgrade to v112 to unenroll if your Chromebook meets the requirements." from `index.html`
- add `<hr />` before a new header in `cryptosmite.html`, such as add `<hr />` before `<h3>Tutorial,/h3>`
- add `<kbd>` & `</bkd>` around the decryption key in `cryptosmite.html`
- change `power+refresh+esc` to `<kbd>Power (⏻) + Reload (↻) + ESC</kbd>` in `cryptosmite.html`
- add `<kbd>` & `</kbd>` around `CTRL + ALT + E` in `cryptosmite.html`
- change `ctrl+d` to `<kbd>CTRL + D</kbd>` in `cryptosmite.html`
- change `root` to `<kbd>root</kbd>` in `cryptosmite.html`
- change `vpd -i RW_VPD -s check_enrollment=0` to `<kbd>vpd -i RW_VPD -s check_enrollment=0</kbd>` in `cryptosmite.html`
- change `ctrl+alt+f2` to `<kbd>CTRL + ALT + F2 (→)</kbd>` in `cryptosmite.html`
- change `if it ends in a 3 you cannot without hacky trickery that isn't covered here.` to `if it ends in a 3, you cannot downgrade.` cause there isn't any "hacky trickery" to change your kernver while enrolled, not without a hardware modification to disable WP and unenroll anyways.
- change `@electronis` to ` <a href="https://discord.com/users/480818241145536513">@electronis</a>` in `cryptosmite.html`
- remove `(and in most cases later versions)` in `cryptosmite.html`, you cannot unenroll on v120 or newer.
- remove `p` from `p<kbd>`, as you added an extra p before a `<kbd>`
- remove "it should begin the 'recovery' (downgrade)" 
- add at the end of "from cros.tech": "Once you plug in the USB, the recovery (downgrade) process should start."
- at "Those 'extra steps'...
  - add `<kbd>` & `</kbd>` to `ctrl+D`
  - change `ctrl+D` to `CTRL + D`
  - change `power+refresh+esc` to the aforementioned one in the request
  - add `<kbd>` * `</kbd>` to `root`
  - capitalize `W` in `welcome to your Chromebook`
  - change the ` to " (quotes)
- change 'extra steps' to "Extra Steps" (quotations, capitalization)
- change "Those 'extra steps'" to "Those "Extra Steps"..."
- change 'kernver' to "kernver"
- change `<kbd>Ctrl + D</kbd>` to `<kbd>CTRL + D</kbd>`
- move "This is currently the recommended method over E-Halcyon" to be the same line as the CryptoSmite text, not as a new line in `index.html`
- move the CryptoSmite text above E-Halcyon in `index.html`
- change "SH1mmer" to "SH1MMER"
- remove "the main [..] method" and just keep it as "If you cannot use SH1MMER"
- add a comma after "if you cannot use SH1MMER", ex: "If you cannot use SH1MMER, you can use CryptoSmite"

2024-04-09 05:50 UTC, iRonict requested changes
Line 192: Replace "E-HALYCON" with "E-HALCYON"

2024-04-09 06:00 UTC, ThisCatLikesCrypto commented
i can't find where that error is, line 192 does not contain 'E-HALCYON' and where it is mentioned it's spelled correctly

2025-09-29 16:16 UTC, ThisCatLikesCrypto commented
closing - putting this to bed

2025-09-29 16:16 UTC, closed without merging